# Generated by Django 3.2 on 2023-05-22 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[(1, 'QUIZ'), (2, 'PESQUISA')], max_length=50)),
                ('criado_por', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pesquisa_criado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pesquisa_modificado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PesquisaPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('pergunta', models.TextField()),
                ('criado_por', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pesquisapergunta_criado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pesquisapergunta_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.pesquisa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PesquisaPerguntaAlternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('texto', models.TextField()),
                ('is_correta', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pesquisaperguntaalternativa_criado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pesquisaperguntaalternativa_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.pesquisapergunta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='galeriamedia',
            name='tipo',
            field=models.CharField(choices=[(1, 'VÍDEO'), (2, 'URL'), (3, 'IMAGEM')], max_length=50),
        ),
        migrations.CreateModel(
            name='PesquisaResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pesquisaresposta_alternativa', to='core.pesquisaperguntaalternativa')),
                ('criado_por', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pesquisaresposta_criado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pesquisaresposta_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pesquisaresposta_pergunta', to='core.pesquisapergunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pesquisaresposta_lider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
