# Generated by Django 3.2 on 2023-05-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230522_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriamedia',
            name='link',
            field=models.CharField(blank=True, default=True, max_length=500),
        ),
    ]
